 /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package message;

import client.Client;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author
 */
public class anasayfa extends javax.swing.JFrame {

    /**
     * Creates new form anasayfa
     */
    public static anasayfa ThisAnasayfa;
    public DefaultListModel users;
    public static String user1, user2, groupName;
    public static Object groupUsers;

    public anasayfa() {
        initComponents();
        ThisAnasayfa = this;
        users = new DefaultListModel();
        list_users.setModel(users);
    }

    /**
     * This method s called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_users = new javax.swing.JList<String>();
        btn_private_mss = new javax.swing.JButton();
        lbl_hesapadi2 = new javax.swing.JLabel();
        lbl_hesapadi = new javax.swing.JLabel();
        btn_create_room = new javax.swing.JButton();
        txt_name = new javax.swing.JTextField();
        btn_connect = new javax.swing.JButton();
        lbl_name = new javax.swing.JLabel();
        lbl_room_name = new javax.swing.JLabel();
        txt_room_name = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(450, 640));
        getContentPane().setLayout(null);

        list_users.setBackground(new java.awt.Color(204, 204, 255));
        list_users.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        list_users.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        list_users.setForeground(new java.awt.Color(0, 51, 153));
        jScrollPane1.setViewportView(list_users);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 80, 430, 290);

        btn_private_mss.setBackground(new java.awt.Color(204, 204, 255));
        btn_private_mss.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_private_mss.setText("Private Message");
        btn_private_mss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_private_mssActionPerformed(evt);
            }
        });
        getContentPane().add(btn_private_mss);
        btn_private_mss.setBounds(230, 380, 210, 60);

        lbl_hesapadi2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        lbl_hesapadi2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_hesapadi2);
        lbl_hesapadi2.setBounds(0, 110, 210, 30);

        lbl_hesapadi.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lbl_hesapadi);
        lbl_hesapadi.setBounds(30, 20, 130, 0);

        btn_create_room.setBackground(new java.awt.Color(204, 204, 255));
        btn_create_room.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_create_room.setText("Create Room");
        btn_create_room.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_create_roomActionPerformed(evt);
            }
        });
        getContentPane().add(btn_create_room);
        btn_create_room.setBounds(10, 380, 210, 60);

        txt_name.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        txt_name.setForeground(new java.awt.Color(102, 102, 102));
        txt_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_name);
        txt_name.setBounds(60, 30, 250, 40);

        btn_connect.setBackground(new java.awt.Color(204, 204, 255));
        btn_connect.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_connect.setText("Connect");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });
        getContentPane().add(btn_connect);
        btn_connect.setBounds(320, 30, 120, 40);

        lbl_name.setForeground(new java.awt.Color(0, 51, 102));
        lbl_name.setText("Name:");
        getContentPane().add(lbl_name);
        lbl_name.setBounds(10, 30, 50, 40);

        lbl_room_name.setForeground(new java.awt.Color(0, 51, 102));
        lbl_room_name.setText("Room Name:");
        getContentPane().add(lbl_room_name);
        lbl_room_name.setBounds(10, 450, 100, 40);
        getContentPane().add(txt_room_name);
        txt_room_name.setBounds(110, 450, 250, 40);

        pack();
    }// </editor-fold>                        

    private void btn_private_mssActionPerformed(java.awt.event.ActionEvent evt) {                                                

        user1 = txt_name.getText();
        user2 = list_users.getSelectedValue().toString();
        ThisAnasayfa.setVisible(false);

        try {
            Room sohbets = new Room(user2);
            sohbets.setVisible(true);
        } catch (InterruptedException ex) {
            Logger.getLogger(anasayfa.class.getName()).log(Level.SEVERE, null, ex);
        }


    }                                               

    private void btn_create_roomActionPerformed(java.awt.event.ActionEvent evt) {                                                

//        ThisAnasayfa.setVisible(false);
//        String message = txt_room_name.getText().toString() + "_";
//        if (list_users.getSelectedIndex() != -1) {
//            for (Object item : list_users.getSelectedValuesList()) {
//                message += item + "-";
//            }
//        }

        groupName = txt_room_name.getText();
        groupUsers = list_users.getSelectedValuesList().toString();
        ThisAnasayfa.setVisible(false);

        try {
            Group grup = new Group(groupName, (String) groupUsers);
            grup.setVisible(true);
        } catch (Exception e) {

        }
    }                                               

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:

        Client.Start("localhost", 7000);
        user1 = txt_name.getText();
        //  txt_name.setText("Your Name :" + txt_name.getText());
        txt_name.setEnabled(false);
        btn_connect.setEnabled(false);


    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anasayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anasayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    public javax.swing.JButton btn_connect;
    private javax.swing.JButton btn_create_room;
    private javax.swing.JButton btn_private_mss;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_hesapadi;
    private javax.swing.JLabel lbl_hesapadi2;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_room_name;
    public javax.swing.JList<String> list_users;
    public static javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_room_name;
    // End of variables declaration                   

}
