/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package message;

import client_project.Client;
import java.awt.Dimension;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author busra
 */
public class arayuz extends javax.swing.JFrame {

    /**
     * Creates new form arayuz
     */
    //framedeki komponentlere erişim için statik sayfa değişkeni
    public static arayuz ThisArayuz;
    public DefaultListModel users;

    public arayuz() {
        initComponents();
        ThisArayuz = this;
        ThisArayuz.setPreferredSize(new Dimension(450, 640));
        users = new DefaultListModel();
        online_users.setModel(users);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        btn_connect = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        online_users = new javax.swing.JList<String>();
        lbl_your_name = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/message/b_1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setMaximumSize(new java.awt.Dimension(450, 640));
        jLabel2.setMinimumSize(new java.awt.Dimension(450, 640));
        jLabel2.setPreferredSize(new java.awt.Dimension(450, 640));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 640));
        getContentPane().setLayout(null);

        txt_name.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_name.setForeground(new java.awt.Color(102, 102, 102));
        txt_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_name.setText("Write your name");
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        getContentPane().add(txt_name);
        txt_name.setBounds(10, 10, 250, 40);

        btn_connect.setBackground(new java.awt.Color(255, 255, 255));
        btn_connect.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btn_connect.setText("Connect");
        btn_connect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connectActionPerformed(evt);
            }
        });
        getContentPane().add(btn_connect);
        btn_connect.setBounds(270, 10, 119, 40);

        online_users.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        online_users.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        online_users.setForeground(new java.awt.Color(0, 51, 153));
        jScrollPane1.setViewportView(online_users);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 290, 260, 340);
        getContentPane().add(lbl_your_name);
        lbl_your_name.setBounds(10, 250, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_connectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connectActionPerformed
        // TODO add your handling code here:
        try {
           Client.Start("localhost", 7000);
           lbl_your_name.setText(txt_name.getText());
        } catch (Exception e) {
            System.out.println("Sisteme bağlanılamadı.");
        }
    }//GEN-LAST:event_btn_connectActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new arayuz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_connect;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_your_name;
    public javax.swing.JList<String> online_users;
    public javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
