/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package message;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Base64;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author busra
 */
public class Group extends javax.swing.JFrame {

    /**
     * Creates new form GrupSohbet
     *
     */
    public static Group ThisGrupSohbet;
    public DefaultListModel kisilerListesi;
    public static String grup_adi;
    public static String kisiler;
    public static File fileToSend = null;

    public Group() {
        initComponents();
        ThisGrupSohbet = this;
        lbl_grupName.setText(anasayfa.groupName);
    }

    public Group(String s) {
        initComponents();
        ThisGrupSohbet = this;
        //   grup_mesaj_akisi.setEditable(true);
        lbl_grupName.setText(anasayfa.groupName);

//
       
//        Thread.sleep(100);
//        ThisGrupSohbet.grup_adi_.setText(grup_adi);
//
//        Message msg = new Message(Message.Message_Type.grupKisiBul);
//        msg.content = grup_adi + "_" + kisiler;
//        Thread.sleep(100);
//        client.Client.Send(msg);
    }

    public Group(String grup_ad, String kisi) throws InterruptedException {
        initComponents();
        ThisGrupSohbet = this;
        System.out.println("group çalıtı");
        ThisGrupSohbet.lbl_grupName.setText(anasayfa.groupName);
//        Message msg = new Message(Message.Message_Type.grupKisiBul);
//        msg.content = grup_adi + "-" + kisiler;
//        Thread.sleep(100);
//        client.Client.Send(msg);

        Thread.sleep(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        grup_mesaj_kutusu = new javax.swing.JTextField();
        btn_mesaj_gonder_grup = new javax.swing.JButton();
        btn_dosya = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        grup_mesaj_akisi = new javax.swing.JTextPane();
        lbl_grupName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 640));
        getContentPane().setLayout(null);

        grup_mesaj_kutusu.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        grup_mesaj_kutusu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(grup_mesaj_kutusu);
        grup_mesaj_kutusu.setBounds(70, 410, 310, 60);

        btn_mesaj_gonder_grup.setText("Send");
        btn_mesaj_gonder_grup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mesaj_gonder_grupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mesaj_gonder_grup);
        btn_mesaj_gonder_grup.setBounds(380, 410, 70, 60);

        btn_dosya.setText("File");
        btn_dosya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dosyaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dosya);
        btn_dosya.setBounds(10, 410, 60, 60);

        grup_mesaj_akisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        grup_mesaj_akisi.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        jScrollPane2.setViewportView(grup_mesaj_akisi);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 60, 440, 340);
        getContentPane().add(lbl_grupName);
        lbl_grupName.setBounds(70, 20, 250, 40);

        pack();
    }// </editor-fold>                        

    private void btn_mesaj_gonder_grupActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        // TODO add your handling code here:
        //eger dosya gonderme durumu yoksa clientin yazdigi mesaji mesaj akisina ekler 
        //tum mesaj akisini karsi clientlara gonderir
        if (fileToSend == null) {
            String ad = client.Client.client_name;
            String n_ad = ad.toUpperCase();
            String icerik = n_ad + ":\n" + grup_mesaj_kutusu.getText().toString() + "\n";
            grup_mesaj_akisi.setText(grup_mesaj_akisi.getText() + icerik);
            grup_mesaj_kutusu.setText("");

            Message msg = new Message(Message.Message_Type.icerikGrup);
            msg.content = kisiler + "_" + grup_mesaj_akisi.getText();
            try {
                Thread.sleep(300);
            } catch (InterruptedException ex) {
                Logger.getLogger(Group.class.getName()).log(Level.SEVERE, null, ex);
            }
            client.Client.Send(msg);
            //dosya gonderme durumu varsa
        } else if (fileToSend != null) {
            try {
                //dosya gonderildi bilgisini mesaj akisina ekler dosya adiyla
                //dosyayi karsiya gonderir
                String ad = client.Client.client_name;
                String n_ad = ad.toUpperCase();
                String icerik = n_ad + ":\n" + "--- Dosya : " + fileToSend.getName() + " ---\n" + grup_mesaj_kutusu.getText().toString() + "\n";
                grup_mesaj_akisi.setText(grup_mesaj_akisi.getText() + icerik);
                grup_mesaj_kutusu.setText("");

                Message msg = new Message(Message.Message_Type.icerikGrup);
                msg.content = kisiler + "_" + grup_mesaj_akisi.getText();
                Thread.sleep(100);
                try {
                    Thread.sleep(300);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Group.class.getName()).log(Level.SEVERE, null, ex);
                }
                client.Client.Send(msg);

                FileInputStream fileInputStream = new FileInputStream(fileToSend);
                String fileName = fileToSend.getName();
                byte[] fileContentBytes = new byte[fileInputStream.available()];
                fileInputStream.read(fileContentBytes);
                fileInputStream.close();
                fileToSend = null;

                String fileContentBytes_string = Base64.getEncoder().encodeToString(fileContentBytes);
                Message msg4 = new Message(Message.Message_Type.dosya1);
                msg4.content = kisiler + "&" + fileName + "_" + fileContentBytes_string;
                client.Client.Send(msg4);
                Thread.sleep(300);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Group.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Group.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(Group.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                                     

    private void btn_dosyaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        //dosya cubugunu acar ve gondermek istenilen dosyayi secmeye yarar
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Choose the file");
        int choose_File = fileChooser.showOpenDialog(this);

        if (choose_File == JFileChooser.APPROVE_OPTION) {
            fileToSend = fileChooser.getSelectedFile();

        }else{
            JOptionPane.showMessageDialog(fileChooser, "Try again");
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Group().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_dosya;
    private javax.swing.JButton btn_mesaj_gonder_grup;
    public javax.swing.JTextPane grup_mesaj_akisi;
    private javax.swing.JTextField grup_mesaj_kutusu;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_grupName;
    // End of variables declaration                   
}
