/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package application;

import client.Client;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author gayeu
 */
public class Group extends javax.swing.JFrame {

    /**
     * Creates new form GrupSohbet
     *
     */
    public static Group ThisGrupSohbet;
    public DefaultListModel kisilerListesi;
    public static String grup_adi;
    public static String kisiler;
    public File fileSelect = null;
    public JFileChooser fileChooser = new JFileChooser();

    public Group() {
        initComponents();
        ThisGrupSohbet = this;
    }

    public Group(String s) throws InterruptedException {
        initComponents();
        ThisGrupSohbet = this;
        grup_mesaj_akisi.setEditable(true);

        Thread.sleep(500);
        String[] parts = s.split("_");
        grup_adi = parts[0];
        kisiler = parts[1];
        Thread.sleep(100);

        ThisGrupSohbet.lbl_grupName.setText("Grup Name: " + grup_adi);
        Message msg = new Message(Message.Message_Type.groupUsers);
        msg.content = grup_adi + "_" + kisiler;

        client.Client.Send(msg);

    }

    public Group(String s, int i) throws InterruptedException {
        initComponents();
        ThisGrupSohbet = this;
        grup_mesaj_akisi.setEditable(true);
        // ThisGrupSohbet.lbl_grupName.setText(anasayfa.groupName);   
        Thread.sleep(500);

        String[] parts3 = s.split("_");
        grup_adi = parts3[0];
        kisiler = parts3[1];
        ThisGrupSohbet.lbl_grupName.setText("Grup Name: " + grup_adi);
        Thread.sleep(100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        grup_mesaj_kutusu = new javax.swing.JTextField();
        btn_mesaj_gonder_grup = new javax.swing.JButton();
        btn_dosya = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        grup_mesaj_akisi = new javax.swing.JTextPane();
        lbl_grupName = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(450, 640));
        getContentPane().setLayout(null);

        grup_mesaj_kutusu.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        grup_mesaj_kutusu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 153, 255)));
        getContentPane().add(grup_mesaj_kutusu);
        grup_mesaj_kutusu.setBounds(10, 420, 310, 60);

        btn_mesaj_gonder_grup.setBackground(new java.awt.Color(204, 204, 255));
        btn_mesaj_gonder_grup.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_mesaj_gonder_grup.setText("Send");
        btn_mesaj_gonder_grup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mesaj_gonder_grupActionPerformed(evt);
            }
        });
        getContentPane().add(btn_mesaj_gonder_grup);
        btn_mesaj_gonder_grup.setBounds(10, 490, 410, 60);

        btn_dosya.setBackground(new java.awt.Color(204, 204, 255));
        btn_dosya.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_dosya.setText("File");
        btn_dosya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dosyaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_dosya);
        btn_dosya.setBounds(330, 420, 90, 60);

        grup_mesaj_akisi.setBackground(new java.awt.Color(204, 204, 255));
        grup_mesaj_akisi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255)));
        grup_mesaj_akisi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        grup_mesaj_akisi.setSelectedTextColor(new java.awt.Color(255, 153, 153));
        jScrollPane2.setViewportView(grup_mesaj_akisi);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 70, 410, 340);
        getContentPane().add(lbl_grupName);
        lbl_grupName.setBounds(110, 20, 290, 40);

        btn_back.setBackground(new java.awt.Color(204, 204, 255));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back);
        btn_back.setBounds(10, 10, 80, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/image.jpg"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jLabel1.setMaximumSize(new java.awt.Dimension(1000, 5000));
        jLabel1.setPreferredSize(new java.awt.Dimension(1000, 2000));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 590);

        pack();
    }// </editor-fold>                        

    private void btn_mesaj_gonder_grupActionPerformed(java.awt.event.ActionEvent evt) {                                                      

        if (fileSelect == null) {

            grup_mesaj_akisi.setText(grup_mesaj_akisi.getText() + application.anasayfa.user1 + ": " + grup_mesaj_kutusu.getText().toString() + "\n");
            grup_mesaj_kutusu.setText("");

            Message msg = new Message(Message.Message_Type.GroupFileSender);
            msg.content = kisiler + "_" + grup_mesaj_akisi.getText();
            client.Client.Send(msg);

        } else if (fileSelect != null) {
            try {
                byte file[] = new byte[(int) fileSelect.length()];
                grup_mesaj_akisi.setText(grup_mesaj_akisi.getText() + application.anasayfa.user1 + ":" + fileSelect.getName() + " \n");

                BufferedInputStream bis = new BufferedInputStream(new FileInputStream(fileSelect));
                bis.read(file, 0, file.length);

                Message message = new Message(Message.Message_Type.SendFile);
                message.fileList = file;
                message.content = fileSelect.getName();
                Client.Send(message);

                Message msg = new Message(Message.Message_Type.GroupFileSender);
                msg.content = kisiler + "_" + grup_mesaj_akisi.getText() + "\n";
                client.Client.Send(msg);

                fileSelect = null;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error");
            }

        }
    }                                                     

    private void btn_dosyaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        //dosya cubugunu acar ve gondermek istenilen dosyayi secmeye yarar
        int selection = fileChooser.showOpenDialog(this);
        if (selection == JFileChooser.APPROVE_OPTION) {
            fileSelect = fileChooser.getSelectedFile();
        }
    }                                         

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {                                         
        ThisGrupSohbet.setVisible(false);
        anasayfa.ThisAnasayfaPage.setVisible(true);

        Message msg = new Message(Message.Message_Type.BackGroup);
        msg.content = kisiler;
        client.Client.Send(msg);

    }                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Group.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Group().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_dosya;
    private javax.swing.JButton btn_mesaj_gonder_grup;
    public javax.swing.JTextPane grup_mesaj_akisi;
    private javax.swing.JTextField grup_mesaj_kutusu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_grupName;
    // End of variables declaration                   
}
